// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_a_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAChirp = `-- name: DeleteAChirp :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteAChirp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAChirp, id)
	return err
}
