// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_password_by_email.sql

package database

import (
	"context"
)

const getPasswordByEmail = `-- name: GetPasswordByEmail :one
SELECT hashed_password
FROM users
WHERE email = $1
`

func (q *Queries) GetPasswordByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordByEmail, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
