// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revoke_refresh_token.sql

package database

import (
	"context"
)

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = NOW(),
	updated_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
