// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_user_email_and_password.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserEmailAndPassword = `-- name: UpdateUserEmailAndPassword :one
UPDATE users
SET email = $2,
	hashed_password = $3,
	updated_at = NOW()
WHERE id = $1
RETURNING id, email, updated_at, created_at
`

type UpdateUserEmailAndPasswordParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

type UpdateUserEmailAndPasswordRow struct {
	ID        uuid.UUID
	Email     string
	UpdatedAt time.Time
	CreatedAt time.Time
}

func (q *Queries) UpdateUserEmailAndPassword(ctx context.Context, arg UpdateUserEmailAndPasswordParams) (UpdateUserEmailAndPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmailAndPassword, arg.ID, arg.Email, arg.HashedPassword)
	var i UpdateUserEmailAndPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
